apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b1zdb73o1-go
  janus-idp.io/tekton: b1zdb73o1-go
  backstage.io/kubernetes-id: b1zdb73o1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b1zdb73o1-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
